global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'tf_serving'
    metrics_path: '/monitoring/prometheus/metrics'
    scheme: https
    static_configs:
      - targets: ['ml-ops-submission-production.up.railway.app:443']
